#' @name Gosset
#' @title Gosset Criminal Finger Data
#' @description This data was generated by dithering the cell counts
#' in the \code{crimtab} available in the base \pkg{stats} package.
#' @usage Gosset
#' @format  A data frame with 3000 observations on 2 variables.
#' \describe{
#'     \item{\code{LMFinger}}{Length of Left Middle Finger (cm).}
#'     \item{\code{Height}}{Height (cm)}
#' }
#' @source  see the man page for \code{crimtab}
#' @keywords datasets
NULL
